# Generated by Django 4.2.11 on 2024-03-08 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_profile_first_name_profile_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="age",
            field=models.PositiveSmallIntegerField(
                default=20,
                validators=[
                    django.core.validators.MinValueValidator(18, "18歳未満は登録できません"),
                    django.core.validators.MaxValueValidator(35, "35歳以上は登録できません"),
                ],
                verbose_name="年齢",
            ),
        ),
    ]
