# Generated by Django 4.2.11 on 2024-03-14 04:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0004_alter_profile_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="directmessage",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="送信時間",
            ),
            preserve_default=False,
        ),
    ]
